FROM ubuntu:20.04

RUN apt-get -y update
RUN apt -y install software-properties-common
RUN add-apt-repository -y ppa:ondrej/php
RUN apt-get -y update
RUN DEBIAN_FRONTEND=noninteractive TZ=Asia/Taipei apt-get -y install tzdata
RUN apt-get -y install nginx php8.0 php8.0-fpm

#COPY nginx-default /etc/nginx/sites-available/default

EXPOSE 80

RUN service nginx start
RUN service php8.0-fpm start

CMD ["/bin/bash"]
